name: Basic React App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build React APP
        run: sudo yarn build
      # - name: Install dependencies
      #   run: npm install

      # - name: Run the tests
      #   run: npm test

      # - name: Build
      #   run: npm run build
      # - name: Install Surge
      #   run: npm install -g surge
      # - name: Run surge
      #   run: surge ./ basic-react-app-test.surge.sh --token ${{ secrets.SURGETOKEN }}

          
